GET http://localhost:3001/api/persons

###
POST http://localhost:3001/api/persons HTTP/1.1
content-type: application/json

{
    "name": "Anna",
    "number": "01-234567"
}

###
PUT http://localhost:3001/api/persons/64c3060ac42fbc7a5fb91b3c
content-type: application/json

{
    "name": "Ada Lovelace",
    "number": "534-1239323",
    "id": "64c3060ac42fbc7a5fb91b3c"
}